import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Movitopia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <nav>
          <h1>logo</h1>
          <h1>
            <a href="/about">About</a>
          </h1>
          <a>Sign Up</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
